package com.quickstart.customDroplets;

import java.io.*;


import javax.servlet.*;

import com.quickstart.services.GenerateItemJob;
import com.quickstart.services.GenerateItems;

import atg.nucleus.ServiceException;
import atg.repository.Repository;
import atg.servlet.*;

public class SimpleServlet extends DynamoServlet {

     private GenerateItems generateItems;

	public SimpleServlet() {

	}

	public void service(DynamoHttpServletRequest request, DynamoHttpServletResponse response)
			throws ServletException, IOException {

		/*
		 * request.setParameter("key", "test droplet");
		 * request.serviceParameter("aff", request, response);
		 * 
		 * 
		 * request.setParameter("key2", "test droplet 2222");
		 * request.serviceParameter("aff2", request, response);
		 */

		/*
		 * ServletOutputStream out = response.getOutputStream (); out.println
		 * ("<h1>I am generated by a java object.</h1>");
		 */
		
         if(generateItems.generateRandomItems()){
        	 ServletOutputStream out = response.getOutputStream (); out.println
    		  ("<h1>successfully added</h1>");
         }else {
        	 ServletOutputStream out = response.getOutputStream (); out.println
    		  ("<h1>Erreur</h1>");
         }
       
	}

	public GenerateItems getGenerateItems() {
		return generateItems;
	}

	public void setGenerateItems(GenerateItems generateItems) {
		this.generateItems = generateItems;
	}


}
